apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: webapp
spec:
  # minReadySeconds: 30
  selector:
    matchLabels:
      app: webapp
  # replicas: 1
  template:
    metadata:
      labels: 
        app: webapp
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release2
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
        resources: 
          requests:
            memory: 300Mi
            cpu: 100m